@echo off
echo Starting WMess projects...
echo.
echo [1/3] Starting API...
start "WMess.Api" cmd /k "dotnet run --project WMess.Api/WMess.Api.csproj --launch-profile http"
echo.
echo Waiting 5 seconds for API to start...
timeout /t 5 /nobreak >nul
echo.
echo [2/3] Starting Web (BFF)...
start "WMess.Web" cmd /k "dotnet run --project WMess.Web/WMess.Web.csproj --launch-profile https"
echo.
echo [3/3] Starting Client (Vite)...
start "WMess.Client" cmd /k "cd WMess.Client && npm run dev"
echo.
echo All three projects are starting...
echo Check the opened windows for output.
echo Open the app at http://localhost:5173
pause
