@echo off
echo Starting WMess projects...
echo.
echo [1/2] Starting API...
start "WMess.Api" cmd /k "dotnet run --project WMess.Api/WMess.Api.csproj"
echo.
echo Waiting 5 seconds for API to start...
timeout /t 5 /nobreak >nul
echo.
echo [2/2] Starting Web...
start "WMess.Web" cmd /k "dotnet run --project WMess.Web/WMess.Web.csproj"
echo.
echo Both projects are starting...
echo Check the opened windows for output.
pause
